export const sites = [
  // FUN & GAMES
  "https://pointerpointer.com",
  "https://hackertyper.net",
  "https://zoomquilt.org",
  "https://radio.garden",
  "https://thispersondoesnotexist.com",
  "https://theuselessweb.com",
  "https://neal.fun",
  "http://en.akinator.com",
  "https://clickclickclick.click",
  "http://www.drawastickman.com",
  "https://patatap.com",
  "http://lospinosdelazucareria.itch.io",
  "https://quickdraw.withgoogle.com",
  "https://weavesilk.com",
  "https://www.staggeringbeauty.com",
  "http://www.twofoods.com",
  "https://strobe.cool",
  "http://ghostsingles.com",
  "https://www.ifixit.com",
  "https://en.lichess.org",
  "https://codecombat.com",
  "http://www.incredibox.com",
  "http://touchpianist.com",
  "https://typatone.com",
  "https://fishbowl-game.com",
  "https://jackboxgames.com",
  "https://typeracer.com",

  // VISUAL & CREATIVE
  "https://www.canva.com",
  "https://draw.io",
  "https://excalidraw.com",
  "https://kleki.com",
  "http://sumopaint.com",
  "https://pixlr.com",
  "https://www.photopea.com",
  "https://www.figma.com",
  "https://www.remove.bg",
  "https://www.calligraphr.com",
  "https://www.calligrapher.ai",
  "https://ribbet.com",
  "http://www.degraeve.com/color-palette",
  "https://dinosaurpictures.org/ancient-earth#170",

  // MUSIC & SOUND
  "http://rainymood.com",
  "http://anasomnia.com",
  "https://relax.li",
  "http://poolside.fm",
  "https://www.pretzel.rocks",
  "https://www.audiocheck.net",
  "https://tunein.com",
  "https://www.spotlistr.com",

  // LEARNING & KNOWLEDGE
  "https://www.16personalities.com",
  "https://www.7cups.com",
  "https://www.etymonline.com",
  "https://explainshell.com",
  "https://betterexplained.com",
  "https://learnxinyminutes.com",
  "https://learngitbranching.js.org",
  "https://alison.com",
  "https://linuxjourney.com",
  "https://egghead.io",
  "https://www.codecademy.com",
  "https://freecodecamp.org",
  "https://www.khanacademy.org",
  "https://algorithm-visualizer.org",
  "https://mlu-explain.github.io",
  "https://cs50.harvard.edu",

  // TOOLS & UTILITIES
  "https://10minutemail.com",
  "https://getnada.com",
  "https://www.canva.com",
  "https://cloudconvert.com",
  "https://www.remove.bg",
  "https://smallpdf.com",
  "https://www.draw.io",
  "https://regex101.com",
  "https://crontab.guru",
  "https://www.wolframalpha.com",
  "https://untools.co",
  "https://www.diffchecker.com",
  "https://www.randomizer.org",
  "https://downforeveryoneorjustme.com",

  // INFORMATION & DISCOVERY
  "https://wikipedia.org",
  "https://www.youtube.com",
  "https://reddit.com",
  "http://www.allyoucanread.com",
  "https://www.bbc.com",
  "http://www.allitebooks.com",
  "https://librivox.org",
  "https://www.onthisday.com",
  "https://www.atlasobscura.com",
  "https://tineye.com",

  // TRAVEL & EXPLORATION
  "http://www.mapcrunch.com",
  "https://randomstreetview.com",
  "https://earth.nullschool.net",
  "https://www.windy.com",
  "https://www.flightradar24.com",
  "https://www.streetview.com",
  "https://www.google.com/maps",
  "https://www.roadtrippers.com",

  // PRODUCTIVITY & LIFE
  "https://www.toggl.com",
  "https://todoist.com",
  "https://www.notion.so",
  "https://www.feedly.com",
  "https://www.futureme.org",
  "https://timeanddate.com",
  "https://www.calendar.google.com",
  "https://www.tomato-timer.com",

  // DESIGN & INSPIRATION
  "https://www.awwwards.com",
  "https://dribbble.com",
  "https://www.behance.net",
  "https://www.pinterest.com",
  "https://unsplash.com",
  "https://www.pexels.com",
  "https://www.flaticon.com",
  "https://www.iconfinder.com",
  "https://fonts.google.com",

  // AI & FUTURE TECH
  "https://www.theresanaiforthat.com",
  "https://aitools.fyi",
  "https://www.openai.com",
  "https://huggingface.co",
  "https://replicate.com",
  "https://www.runwayml.com",

  // WEIRD & RANDOM
  "http://www.fallingfalling.com",
  "http://ffffidget.com",
  "http://www.staggeringbeauty.com",
  "http://weirdorconfusing.com",
  "http://www.nothingprivate.ml",
  "http://motherfuckingwebsite.com",
  "https://www.theworstwebsiteinthe.world",
  "http://www.iamawesome.com",
  "https://archive.org",
  "http://www.oldversion.com",

  // DEVELOPMENT RESOURCES
  "https://github.com",
  "https://stackoverflow.com",
  "https://www.npmjs.com",
  "https://caniuse.com",
  "https://devdocs.io",
  "https://css-tricks.com",
  "https://web.dev",
  "https://webdesign.tutsplus.com",

  // PRODUCTIVITY HACKS
  "https://www.wastemytime.com",
  "https://www.reddit.com/r/InternetIsBeautiful",
  "https://www.vice.com",
  "https://www.theverge.com",
  "https://www.wired.com",
  "https://www.arstechnica.com",
];

export function getRandomSite() {
  return sites[Math.floor(Math.random() * sites.length)];
}

